# =============================================================================
# MAKEFILE - Deadlock Detection System Build Configuration
# =============================================================================
# Build system for deadlock detection project with support for parallel builds
# and automatic dependency tracking.
# =============================================================================

# Compiler and flags
CC := gcc
CFLAGS := -Wall -Wextra -O2 -std=c99 -D_POSIX_C_SOURCE=200809L -g
LDFLAGS := -lpthread

# Directories
SRC_DIR := src
OBJ_DIR := obj
BIN_DIR := bin
TEST_DIR := test

# Include directory for compilation
INCLUDES := -I$(SRC_DIR)

# Source files (excluding main.c for library objects)
SRC_FILES := $(wildcard $(SRC_DIR)/*.c)
LIB_SRC_FILES := $(filter-out $(SRC_DIR)/main.c,$(SRC_FILES))

# Object files
LIB_OBJS := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(LIB_SRC_FILES))
MAIN_OBJ := $(OBJ_DIR)/main.o

# Test source files
TEST_SRCS := $(wildcard $(TEST_DIR)/test_*.c)
TEST_TARGETS := $(patsubst $(TEST_DIR)/test_%.c,$(BIN_DIR)/test_%,$(TEST_SRCS))

# Main executable
TARGET := $(BIN_DIR)/deadlock_detector

# Dependency files (generated by -MMD flag)
DEP_FILES := $(LIB_OBJS:.o=.d) $(MAIN_OBJ:.o=.d)

# =============================================================================
# BUILD TARGETS
# =============================================================================

.PHONY: all clean test help install

# Default target
all: $(TARGET)
	@echo "========================================="
	@echo "Build successful: $(TARGET)"
	@echo "========================================="

# Main executable
$(TARGET): $(BIN_DIR) $(MAIN_OBJ) $(LIB_OBJS)
	@echo "Linking $(TARGET)..."
	$(CC) $(CFLAGS) -o $@ $(MAIN_OBJ) $(LIB_OBJS) $(LDFLAGS)

# Create directories
$(OBJ_DIR) $(BIN_DIR):
	@mkdir -p $@

# Compile library source files (with dependency tracking)
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	@echo "Compiling $<..."
	$(CC) $(CFLAGS) $(INCLUDES) -MMD -MP -c $< -o $@

# Compile main.c
$(MAIN_OBJ): $(SRC_DIR)/main.c | $(OBJ_DIR)
	@echo "Compiling $(SRC_DIR)/main.c..."
	$(CC) $(CFLAGS) $(INCLUDES) -MMD -MP -c $< -o $@

# Test targets
test: $(TEST_TARGETS)
	@echo ""
	@echo "========================================="
	@echo "Running all tests..."
	@echo "========================================="
	@failed=0; \
	for test in $(TEST_TARGETS); do \
		echo ""; \
		echo "Running $$test..."; \
		echo "----------------------------------------"; \
		./$$test || failed=$$((failed + 1)); \
	done; \
	echo ""; \
	echo "========================================="; \
	if [ $$failed -eq 0 ]; then \
		echo "All tests PASSED ✓"; \
		exit 0; \
	else \
		echo "Some tests FAILED ✗ ($$failed failed)"; \
		exit 1; \
	fi

# Build test executables
$(BIN_DIR)/test_%: $(TEST_DIR)/test_%.c $(LIB_OBJS) | $(BIN_DIR)
	@echo "Building test: $@"
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $< $(LIB_OBJS) $(LDFLAGS)

# Individual test targets
test-graph: $(BIN_DIR)/test_graph
	@echo "Running test_graph..."
	./$(BIN_DIR)/test_graph

test-cycle: $(BIN_DIR)/test_cycle
	@echo "Running test_cycle..."
	./$(BIN_DIR)/test_cycle

test-system: $(BIN_DIR)/test_system
	@echo "Running test_system..."
	./$(BIN_DIR)/test_system

# Clean build artifacts
clean:
	@echo "Cleaning build artifacts..."
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Clean completed"

# Help message
help:
	@echo "========================================="
	@echo "Deadlock Detection System - Makefile Help"
	@echo "========================================="
	@echo ""
	@echo "Available targets:"
	@echo "  make all          - Build the main executable ($(TARGET))"
	@echo "  make test         - Build and run all unit tests"
	@echo "  make test-graph   - Build and run graph tests only"
	@echo "  make test-cycle   - Build and run cycle detection tests only"
	@echo "  make test-system  - Build and run system integration tests only"
	@echo "  make clean        - Remove all build artifacts (obj/, bin/)"
	@echo "  make help         - Show this help message"
	@echo ""
	@echo "Build options:"
	@echo "  make -jN          - Build in parallel with N jobs (e.g., make -j4)"
	@echo ""
	@echo "Output files:"
	@echo "  $(TARGET)         - Main executable"
	@echo "  $(BIN_DIR)/test_* - Test executables"
	@echo "  $(OBJ_DIR)/*.o    - Object files"
	@echo "  $(OBJ_DIR)/*.d    - Dependency files"
	@echo ""
	@echo "Example usage:"
	@echo "  make              # Build main executable"
	@echo "  make test         # Run all tests"
	@echo "  make clean        # Clean build files"
	@echo "  make -j4          # Parallel build with 4 jobs"

# Include dependency files (if they exist)
-include $(DEP_FILES)

# =============================================================================
# END OF MAKEFILE
# =============================================================================

